export const LOGIN_SUCCESS = 'LOGIN-SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOAD_USER_POLLS = 'LOAD_USER_POLLS';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';
export const CLEAR_PROFILE_DATA = 'CLEAR_PROFILE_DATA';

export const LOAD_HOTTEST_POLLS = 'LOAD_HOTTEST_POLLS';
export const SET_HOTTEST_POLLS = 'SET_HOTTEST_POLLS';
export const CLEAR_HOTTEST_POLLS = 'CLEAR_HOTTEST_POLLS';

export const LOAD_SEARCHED_POLLS = 'LOAD_SEARCHED_POLLS';
export const SET_SEARCHED_POLLS = 'SET_SEARCHED_POLLS';
export const CLEAR_SEARCHED_POLLS = 'CLEAR_SEARCHED_POLLS';

export const LOAD_POLL_DATA = 'LOAD_POLL_DATA';
export const GET_POLL_DATA = 'GET_POLL_DATA';
export const CLEAR_POLL_DATA = 'CLEAR_POLL_DATA';